// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EPDwfFdudx2mIbd1ugpDsBZZPCfuMoQ',
    appId: '1:564419249966:web:ae1f18872e97a608d7dcbf',
    messagingSenderId: '564419249966',
    projectId: 'fluttergram-1a880',
    authDomain: 'fluttergram-1a880.firebaseapp.com',
    storageBucket: 'fluttergram-1a880.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFDovKYgoohJqtvNgLFeLbOuaXOvKecw',
    appId: '1:564419249966:android:fa3a6dca7b4e0e1dd7dcbf',
    messagingSenderId: '564419249966',
    projectId: 'fluttergram-1a880',
    storageBucket: 'fluttergram-1a880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZ5Y20paXXjrqRUF5lywlV93Ax1MykAY',
    appId: '1:564419249966:ios:c7cd39633f2b1136d7dcbf',
    messagingSenderId: '564419249966',
    projectId: 'fluttergram-1a880',
    storageBucket: 'fluttergram-1a880.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

}